[project]
name = "xum"
version = "0.2.0"
description = "Manage Tmux session for selected folders and SSH hosts"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "pyinstaller>=6.15.0",
    "ruff>=0.12.10",
]

[project.scripts]
xum = "xum.main:app"
